apiVersion: apps/v1
kind: Deployment
metadata:
  name: datagen-zz-${ENV}-deployment
  namespace: ${ENV}-fizzbuzz
  labels:
    app: fizz-buzz-datagen-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fizz-buzz-datagen
  template:
    metadata:
      labels:
        app: fizz-buzz-datagen
    spec:
      containers:
        - name: datagen-zz-${ENV}-container
          image: gcr.io/loicmdivad-pse2020/fizz-buzz-generator:latest
          env:
            - name: INPUT_TOPIC_NAME
              value: input-event-${ENV}
            - name: OUTPUT_TOPIC_NAME
              value: output-event-${ENV}
            - name: CLIENT_ID
              value: "0"

            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: ${ENV}-secretzz
                  key: api-key
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ${ENV}-secretzz
                  key: secret-key
            - name: BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: ${ENV}-secretzz
                  key: bootstrap-servers
            - name: SR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ${ENV}-secretzz
                  key: sr-api-key
            - name: SR_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ${ENV}-secretzz
                  key: sr-secret-key
            - name: SCHEMA_REGISTRY_URL
              valueFrom:
                secretKeyRef:
                  name: ${ENV}-secretzz
                  key: schema-registry-url
            - name: SASL_CLASS
              valueFrom:
                secretKeyRef:
                  name: ${ENV}-secretzz
                  key: sasl-class
            - name: ROOT_LOG_LVL
              value: DEBUG
            - name: FBZZ_LOG_LVL
              value: DEBUG
