name: Feature Workflow

on:
  push:
    branches-ignore:
      - 'release/*'
      - 'wip/**'
      - 'master'

jobs:
  main:
    name: Feature Workflow Job
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout Fizz Buzz Streaming App
        uses: actions/checkout@v1

      - name: Maven Unit Tests
        run: ./mvnw -B test
        # delete this after once the CI is properly set up
        continue-on-error: true

      - name: Maven It Tests
        run: ./mvnw -B integration-test -Dit.only
