name: Master Workflow

on:
  push:
    branches:
      - 'master'

jobs:
  main:
    name: Master Workflow Job
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout Fizz Buzz Streaming App
        uses: actions/checkout@v1

      - name: Maven Unit Tests
        run: ./mvnw -B test jacoco:report
        # delete this after once the CI is properly set up
        continue-on-error: true

      - name: Coveralls Test Coverage Report
        run: ./mvnw -B coveralls:report -Dcoveralls.token=${{ secrets.COVERALLS_TOKEN }} -Dbranch=master
        # delete this after once the CI is properly set up
        continue-on-error: true

      - name: Maven It Tests
        run: ./mvnw -B integration-test -Dit.only
